### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by donavon** [YuzuJS/storeit-value#6]
To help mitigate memory leaks, listen to a store's "removed"` event (for this key) and turn off any storeit-value listeners. Currently, you are listening to a store's "modified" event for all of eternity, long after it may have been deleted.

**Comment by donavon** [comment]
You should also stop setting to the store when the value has been removed and maybe publishing a "removed" event yourself there chief.

**Comment by pbouzakis** [comment]
Resolved by #10
